import { Location, VoucherBranch, NavItem, JobPosition, Benefit } from "@/types";

export const siteConfig = {
  name: "AK BARBERS",
  url: "https://www.akbarber.com",
  description:
    "Síť prémiových barbershopů v České republice a na Slovensku. Kvalitní pánské stříhání, úprava vousů a skvělý zážitek.",
  phone: "+420 779 502 831",
  email: "info@akbarber.com",
  social: {
    facebook: "https://www.facebook.com/people/Akbarberscz/100079448784976/",
    instagram: "https://www.instagram.com/ak.barbers.cz/",
  },
  booking: "https://booqme.cz",
  legal: {
    cookies: "https://www.akbarber.com/zasady-pouzivani-souboru-cookie-eu/",
    privacy: "https://www.akbarber.com/prohlaseni-o-ochrane-osobnich-udaju/",
  },
};

export const navItems: NavItem[] = [
  { label: "Provozovny", href: "/" },
  { label: "Dárkové poukázky", href: "/#vouchers" },
  { label: "Kariéra", href: "/kariera" },
  { label: "Akademie", href: "/academy" },
  { label: "Kontakt", href: "/#kontakt" },
];

export const locations: Location[] = [
  {
    id: "beroun",
    name: "AK BARBERS Beroun",
    city: "Beroun",
    address: "Havlíčkova 128, 266 01 Beroun-centrum",
    phone: "+420 779 502 831",
    openingHours: [
      { days: "Po – Pá", hours: "9:00 – 18:00" },
      { days: "So – Ne", hours: "9:00 – 14:00" },
    ],
    type: "walk-in",
    services: [
      { name: "Klasické pánské stříhání", price: "449 Kč", description: "Konzultace, precizní střih vlasů na míru strojem nebo nůžkami, úprava a konečný styling vlasů." },
      { name: "Skin Fade / dlouhé vlasy", price: "499 Kč", description: "Skin Fade – konzultace, čistý/střední/vousový fade, střih strojem od 0 mm, použití shaveru, precizní přechody, úprava a konečný styling." },
      { name: "Senior pánský střih (65+)", price: "299 Kč", description: "Střih pro starší pány od 65 let." },
      { name: "Dětský střih (1–15 let)", price: "349 Kč / 449 Kč", description: "Stříhání mladých mužů ve věku od 1 do 15 let. Klasický střih, focusový, styling. Skin Fade / Low Fade / Crop Fade / Buzz Cut +100 Kč." },
      { name: "Úprava vousů", price: "399 Kč", description: "Konzultace, úprava vousů strojkem a nůžkami, celkem břitvou na vybledení, aplikace pečující kosmetiky, konečná úprava." },
      { name: "Střih vlasů a úprava vousů", price: "799 Kč", description: "Konzultace, klasický střih vlasů strojkem, úprava vousů, aplikace pečující kosmetiky na vousy, úprava a celkový styling vlasů a vousů." },
    ],
    image: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800&q=80",
    currency: "CZK",
    googleMapsUrl: "https://share.google/p6mtjgPNIp3zPfXU0",
    reviewRating: 4.8,
    reviewCount: "180+",
    rankText: "Top #1 Barbershop v Berouně podle Googlu",
    mapQuery: "AK+Barbers,+Havlickova+128,+Beroun",
  },
  {
    id: "beroun-2",
    name: "AK BARBERS Beroun 2",
    city: "Beroun",
    address: "Plzeňská 145/49, 266 01 Beroun-Město",
    phone: "+420 779 502 831",
    openingHours: [
      { days: "Po – Pá", hours: "9:00 – 18:00" },
      { days: "So – Ne", hours: "9:00 – 14:00" },
    ],
    type: "reservation",
    bookingUrl: "https://booqme.cz/cs/rezervace/ak-barbers-beroun",
    services: [
      { name: "Klasické pánské stříhání", price: "449 Kč", description: "Konzultace, precizní střih vlasů na míru strojem nebo nůžkami, úprava a konečný styling vlasů." },
      { name: "Skin Fade / dlouhé vlasy", price: "499 Kč", description: "Skin Fade – konzultace, čistý/střední/vousový fade, střih strojem od 0 mm, použití shaveru, precizní přechody, úprava a konečný styling." },
      { name: "Senior pánský střih (65+)", price: "299 Kč", description: "Střih pro starší pány od 65 let." },
      { name: "Dětský střih (1–15 let)", price: "349 Kč / 449 Kč", description: "Stříhání mladých mužů ve věku od 1 do 15 let. Klasický střih, focusový, styling. Skin Fade / Low Fade / Crop Fade / Buzz Cut +100 Kč." },
      { name: "Úprava vousů", price: "399 Kč", description: "Konzultace, úprava vousů strojkem a nůžkami, celkem břitvou na vybledení, aplikace pečující kosmetiky, konečná úprava." },
      { name: "Střih vlasů a úprava vousů", price: "799 Kč", description: "Konzultace, klasický střih vlasů strojkem, úprava vousů, aplikace pečující kosmetiky na vousy, úprava a celkový styling vlasů a vousů." },
    ],
    image: "https://images.unsplash.com/photo-1585747860019-8a1d2481c8f5?w=800&q=80",
    note: "Rezervace VIP Club",
    currency: "CZK",
    googleMapsUrl: "https://share.google/YGI5mdYa1BGLt9Tmd",
    reviewRating: 4.9,
    reviewCount: "120+",
    rankText: "Top Barbershop v Berouně podle Googlu",
    mapQuery: "AK+Barbers,+Plzenska+145,+Beroun",
  },
  {
    id: "praha-6",
    name: "AK BARBERS Praha 6",
    city: "Praha",
    address: "Bělohorská 1393/44, 169 00 Praha 6",
    phone: "+420 779 502 831",
    openingHours: [
      { days: "Po – Pá", hours: "9:00 – 18:00" },
      { days: "So – Ne", hours: "9:00 – 14:00" },
    ],
    type: "walk-in + reservation",
    services: [
      { name: "Klasické pánské stříhání", price: "449 Kč", description: "Konzultace, precizní střih vlasů na míru strojem nebo nůžkami, úprava a konečný styling vlasů." },
      { name: "Skin Fade / dlouhé vlasy", price: "499 Kč", description: "Skin Fade – konzultace, čistý/střední/vousový fade, střih strojem od 0 mm, použití shaveru, precizní přechody, úprava a konečný styling." },
      { name: "Senior pánský střih (65+)", price: "299 Kč", description: "Střih pro starší pány od 65 let." },
      { name: "Dětský střih (1–15 let)", price: "349 Kč / 449 Kč", description: "Stříhání mladých mužů ve věku od 1 do 15 let. Klasický střih, focusový, styling. Skin Fade / Low Fade / Crop Fade / Buzz Cut +100 Kč." },
      { name: "Úprava vousů", price: "399 Kč", description: "Konzultace, úprava vousů strojkem a nůžkami, celkem břitvou na vybledení, aplikace pečující kosmetiky, konečná úprava." },
      { name: "Střih vlasů a úprava vousů", price: "799 Kč", description: "Konzultace, klasický střih vlasů strojkem, úprava vousů, aplikace pečující kosmetiky na vousy, úprava a celkový styling vlasů a vousů." },
    ],
    image: "https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=800&q=80",
    currency: "CZK",
    googleMapsUrl: "https://share.google/D6Aq8iH1IZYVxIqrA",
    reviewRating: 4.8,
    reviewCount: "250+",
    rankText: "Top #1 Barbershop na Praze 6 podle Googlu",
    mapQuery: "AK+Barbers,+Belohorska+1393,+Praha+6",
  },
  {
    id: "praha-1",
    name: "AK BARBERS Praha 1",
    city: "Praha",
    address: "Národní 949/19, 110 00 Staré Město",
    phone: "+420 779 502 831",
    openingHours: [
      { days: "Po – Pá", hours: "9:00 – 18:00" },
      { days: "So – Ne", hours: "9:00 – 14:00" },
    ],
    type: "walk-in + reservation",
    bookingUrl: "https://booqme.cz",
    services: [
      { name: "Klasické pánské stříhání", price: "449 Kč", description: "Konzultace, precizní střih vlasů na míru strojem nebo nůžkami, úprava a konečný styling vlasů." },
      { name: "Skin Fade / dlouhé vlasy", price: "499 Kč", description: "Skin Fade – konzultace, čistý/střední/vousový fade, střih strojem od 0 mm, použití shaveru, precizní přechody, úprava a konečný styling." },
      { name: "Senior pánský střih (65+)", price: "299 Kč", description: "Střih pro starší pány od 65 let." },
      { name: "Dětský střih (1–15 let)", price: "349 Kč / 449 Kč", description: "Stříhání mladých mužů ve věku od 1 do 15 let. Klasický střih, focusový, styling. Skin Fade / Low Fade / Crop Fade / Buzz Cut +100 Kč." },
      { name: "Úprava vousů", price: "399 Kč", description: "Konzultace, úprava vousů strojkem a nůžkami, celkem břitvou na vybledení, aplikace pečující kosmetiky, konečná úprava." },
      { name: "Střih vlasů a úprava vousů", price: "799 Kč", description: "Konzultace, klasický střih vlasů strojkem, úprava vousů, aplikace pečující kosmetiky na vousy, úprava a celkový styling vlasů a vousů." },
    ],
    image: "https://images.unsplash.com/photo-1599351431202-1e0f0137899a?w=800&q=80",
    currency: "CZK",
    googleMapsUrl: "https://share.google/ieWwYNLKRsKPQlx6a",
    reviewRating: 4.9,
    reviewCount: "300+",
    rankText: "Top #1 Barbershop v centru Prahy podle Googlu",
    mapQuery: "AK+Barbers,+Narodni+949,+Praha+1",
  },
  {
    id: "kraluv-dvur",
    name: "AK BARBERS Králův Dvůr",
    city: "Králův Dvůr",
    address: "Plzeňská 396, 267 01 Králův Dvůr",
    phone: "+420 779 502 831",
    openingHours: [
      { days: "Po – Pá", hours: "9:00 – 18:00" },
      { days: "So – Ne", hours: "9:00 – 14:00" },
    ],
    type: "walk-in + reservation",
    services: [
      { name: "Klasické pánské stříhání", price: "449 Kč", description: "Konzultace, precizní střih vlasů na míru strojem nebo nůžkami, úprava a konečný styling vlasů." },
      { name: "Skin Fade / dlouhé vlasy", price: "499 Kč", description: "Skin Fade – konzultace, čistý/střední/vousový fade, střih strojem od 0 mm, použití shaveru, precizní přechody, úprava a konečný styling." },
      { name: "Senior pánský střih (65+)", price: "299 Kč", description: "Střih pro starší pány od 65 let." },
      { name: "Dětský střih (1–15 let)", price: "349 Kč / 449 Kč", description: "Stříhání mladých mužů ve věku od 1 do 15 let. Klasický střih, focusový, styling. Skin Fade / Low Fade / Crop Fade / Buzz Cut +100 Kč." },
      { name: "Úprava vousů", price: "399 Kč", description: "Konzultace, úprava vousů strojkem a nůžkami, celkem břitvou na vybledení, aplikace pečující kosmetiky, konečná úprava." },
      { name: "Střih vlasů a úprava vousů", price: "799 Kč", description: "Konzultace, klasický střih vlasů strojkem, úprava vousů, aplikace pečující kosmetiky na vousy, úprava a celkový styling vlasů a vousů." },
    ],
    image: "https://images.unsplash.com/photo-1622286342621-4bd786c2447c?w=800&q=80",
    currency: "CZK",
    googleMapsUrl: "https://share.google/a01WYK1dXrVqUnAbR",
    reviewRating: 4.8,
    reviewCount: "90+",
    rankText: "Top Barbershop v Králově Dvoře podle Googlu",
    mapQuery: "AK+Barbers,+Plzenska+396,+Kraluv+Dvur",
  },
  {
    id: "plzen",
    name: "AK BARBERS Plzeň",
    city: "Plzeň",
    address: "Gerská 2030/23, 323 00 Plzeň 1-Bolevec",
    phone: "+420 779 502 831",
    openingHours: [
      { days: "Po – Pá", hours: "9:00 – 18:00" },
      { days: "So – Ne", hours: "9:00 – 14:00" },
    ],
    type: "walk-in + reservation",
    bookingUrl: "https://booqme.cz/cs/rezervace/ak-barbers-plzen1",
    services: [
      { name: "Klasické pánské stříhání", price: "449 Kč", description: "Konzultace, precizní střih vlasů na míru strojem nebo nůžkami, úprava a konečný styling vlasů." },
      { name: "Skin Fade / dlouhé vlasy", price: "499 Kč", description: "Skin Fade – konzultace, čistý/střední/vousový fade, střih strojem od 0 mm, použití shaveru, precizní přechody, úprava a konečný styling." },
      { name: "Senior pánský střih (65+)", price: "299 Kč", description: "Střih pro starší pány od 65 let." },
      { name: "Dětský střih (1–15 let)", price: "349 Kč / 449 Kč", description: "Stříhání mladých mužů ve věku od 1 do 15 let. Klasický střih, focusový, styling. Skin Fade / Low Fade / Crop Fade / Buzz Cut +100 Kč." },
      { name: "Úprava vousů", price: "399 Kč", description: "Konzultace, úprava vousů strojkem a nůžkami, celkem břitvou na vybledení, aplikace pečující kosmetiky, konečná úprava." },
      { name: "Střih vlasů a úprava vousů", price: "799 Kč", description: "Konzultace, klasický střih vlasů strojkem, úprava vousů, aplikace pečující kosmetiky na vousy, úprava a celkový styling vlasů a vousů." },
    ],
    image: "https://images.unsplash.com/photo-1587909209111-5097ee578ec3?w=800&q=80",
    currency: "CZK",
    googleMapsUrl: "https://share.google/uDA8gpYTfzP3aXRaL",
    reviewRating: 4.9,
    reviewCount: "215+",
    rankText: "Top #1 Barbershop v Plzni podle Googlu",
    mapQuery: "AK+Barbers,+Gerska+2030,+Plzen",
  },
  {
    id: "horovice",
    name: "AK BARBERS Hořovice",
    city: "Hořovice",
    address: "Fügnerova 374/1, 268 01 Hořovice",
    phone: "+420 779 502 831",
    openingHours: [
      { days: "Po – Pá", hours: "9:00 – 18:00" },
      { days: "So – Ne", hours: "9:00 – 14:00" },
    ],
    type: "walk-in + reservation",
    services: [
      { name: "Klasické pánské stříhání", price: "449 Kč", description: "Konzultace, precizní střih vlasů na míru strojem nebo nůžkami, úprava a konečný styling vlasů." },
      { name: "Skin Fade / dlouhé vlasy", price: "499 Kč", description: "Skin Fade – konzultace, čistý/střední/vousový fade, střih strojem od 0 mm, použití shaveru, precizní přechody, úprava a konečný styling." },
      { name: "Senior pánský střih (65+)", price: "299 Kč", description: "Střih pro starší pány od 65 let." },
      { name: "Dětský střih (1–15 let)", price: "349 Kč / 449 Kč", description: "Stříhání mladých mužů ve věku od 1 do 15 let. Klasický střih, focusový, styling. Skin Fade / Low Fade / Crop Fade / Buzz Cut +100 Kč." },
      { name: "Úprava vousů", price: "399 Kč", description: "Konzultace, úprava vousů strojkem a nůžkami, celkem břitvou na vybledení, aplikace pečující kosmetiky, konečná úprava." },
      { name: "Střih vlasů a úprava vousů", price: "799 Kč", description: "Konzultace, klasický střih vlasů strojkem, úprava vousů, aplikace pečující kosmetiky na vousy, úprava a celkový styling vlasů a vousů." },
    ],
    image: "https://images.unsplash.com/photo-1596728325488-58c87691e9af?w=800&q=80",
    currency: "CZK",
    googleMapsUrl: "https://share.google/sW4uoZKb3Zt20YEZC",
    reviewRating: 4.8,
    reviewCount: "100+",
    rankText: "Top Barbershop v Hořovicích podle Googlu",
    mapQuery: "AK+Barbers,+Fugnerova+374,+Horovice",
  },
  {
    id: "slany",
    name: "AK BARBERS Slaný",
    city: "Slaný",
    address: "Třebízského 182, 274 01 Slaný",
    phone: "+420 779 502 831",
    openingHours: [
      { days: "Po – Pá", hours: "9:00 – 18:00" },
      { days: "So – Ne", hours: "9:00 – 14:00" },
    ],
    type: "walk-in + reservation",
    services: [
      { name: "Klasické pánské stříhání", price: "449 Kč", description: "Konzultace, precizní střih vlasů na míru strojem nebo nůžkami, úprava a konečný styling vlasů." },
      { name: "Skin Fade / dlouhé vlasy", price: "499 Kč", description: "Skin Fade – konzultace, čistý/střední/vousový fade, střih strojem od 0 mm, použití shaveru, precizní přechody, úprava a konečný styling." },
      { name: "Senior pánský střih (65+)", price: "299 Kč", description: "Střih pro starší pány od 65 let." },
      { name: "Dětský střih (1–15 let)", price: "349 Kč / 449 Kč", description: "Stříhání mladých mužů ve věku od 1 do 15 let. Klasický střih, focusový, styling. Skin Fade / Low Fade / Crop Fade / Buzz Cut +100 Kč." },
      { name: "Úprava vousů", price: "399 Kč", description: "Konzultace, úprava vousů strojkem a nůžkami, celkem břitvou na vybledení, aplikace pečující kosmetiky, konečná úprava." },
      { name: "Střih vlasů a úprava vousů", price: "799 Kč", description: "Konzultace, klasický střih vlasů strojkem, úprava vousů, aplikace pečující kosmetiky na vousy, úprava a celkový styling vlasů a vousů." },
    ],
    image: "https://images.unsplash.com/photo-1493256338651-d82f7acb2b38?w=800&q=80",
    currency: "CZK",
    googleMapsUrl: "https://share.google/FJWH7veDQhP51zzBR",
    reviewRating: 4.7,
    reviewCount: "85+",
    rankText: "Top Barbershop ve Slaném podle Googlu",
    mapQuery: "AK+Barbers,+Trebizského+182,+Slany",
  },
  {
    id: "maj",
    name: "AK BARBERS Máj",
    city: "Máj",
    address: "Máj 632/36, 370 02 České Budějovice",
    phone: "+420 779 502 831",
    openingHours: [
      { days: "Po – Pá", hours: "9:00 – 18:00" },
      { days: "So – Ne", hours: "9:00 – 14:00" },
    ],
    type: "walk-in + reservation",
    services: [
      { name: "Klasické pánské stříhání", price: "449 Kč", description: "Konzultace, precizní střih vlasů na míru strojem nebo nůžkami, úprava a konečný styling vlasů." },
      { name: "Skin Fade / dlouhé vlasy", price: "499 Kč", description: "Skin Fade – konzultace, čistý/střední/vousový fade, střih strojem od 0 mm, použití shaveru, precizní přechody, úprava a konečný styling." },
      { name: "Senior pánský střih (65+)", price: "299 Kč", description: "Střih pro starší pány od 65 let." },
      { name: "Dětský střih (1–15 let)", price: "349 Kč / 449 Kč", description: "Stříhání mladých mužů ve věku od 1 do 15 let. Klasický střih, focusový, styling. Skin Fade / Low Fade / Crop Fade / Buzz Cut +100 Kč." },
      { name: "Úprava vousů", price: "399 Kč", description: "Konzultace, úprava vousů strojkem a nůžkami, celkem břitvou na vybledení, aplikace pečující kosmetiky, konečná úprava." },
      { name: "Střih vlasů a úprava vousů", price: "799 Kč", description: "Konzultace, klasický střih vlasů strojkem, úprava vousů, aplikace pečující kosmetiky na vousy, úprava a celkový styling vlasů a vousů." },
    ],
    image: "https://images.unsplash.com/photo-1605497788044-5a32c7078486?w=800&q=80",
    currency: "CZK",
    googleMapsUrl: "https://share.google/ieWwYNLKRsKPQlx6a",
    reviewRating: 4.8,
    reviewCount: "70+",
    rankText: "Top Barbershop v Českých Budějovicích podle Googlu",
    mapQuery: "AK+Barbers,+Maj,+Ceske+Budejovice",
  },
  {
    id: "nitra",
    name: "AK BARBERS Nitra",
    city: "Nitra",
    address: "OC AK Mall, Diaľničná trieda 30/31, 949 01 Nitra",
    phone: "+421 XXX XXX XXX",
    openingHours: [
      { days: "Po – Pá", hours: "9:00 – 18:00" },
      { days: "So – Ne", hours: "9:00 – 14:00" },
    ],
    type: "walk-in",
    services: [
      { name: "Klasické pánské stříhání", price: "449 Kč", description: "Konzultace, precizní střih vlasů na míru strojem nebo nůžkami, úprava a konečný styling vlasů." },
      { name: "Skin Fade / dlouhé vlasy", price: "499 Kč", description: "Skin Fade – konzultace, čistý/střední/vousový fade, střih strojem od 0 mm, použití shaveru, precizní přechody, úprava a konečný styling." },
      { name: "Senior pánský střih (65+)", price: "299 Kč", description: "Střih pro starší pány od 65 let." },
      { name: "Dětský střih (1–15 let)", price: "349 Kč / 449 Kč", description: "Stříhání mladých mužů ve věku od 1 do 15 let. Klasický střih, focusový, styling. Skin Fade / Low Fade / Crop Fade / Buzz Cut +100 Kč." },
      { name: "Úprava vousů", price: "399 Kč", description: "Konzultace, úprava vousů strojkem a nůžkami, celkem břitvou na vybledení, aplikace pečující kosmetiky, konečná úprava." },
      { name: "Střih vlasů a úprava vousů", price: "799 Kč", description: "Konzultace, klasický střih vlasů strojkem, úprava vousů, aplikace pečující kosmetiky na vousy, úprava a celkový styling vlasů a vousů." },
    ],
    image: "https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?w=800&q=80",
    currency: "CZK",
    googleMapsUrl: "https://share.google/Z8bxzReTOnT3wrXQz",
    reviewRating: 4.8,
    reviewCount: "95+",
    rankText: "Top Barbershop v Nitre podle Googlu",
    mapQuery: "AK+Barbers,+Nitra",
  },
];

export const representativeServices = [
  { name: "Klasické pánské stříhání", price: "od 399 Kč", description: "Profesionální střih přizpůsobený vašemu stylu" },
  { name: "Skin Fade / dlouhé vlasy", price: "od 499 Kč", description: "Precizní fade a práce s delšími vlasy" },
  { name: "Úprava vousů", price: "od 349 Kč", description: "Tvarování a úprava vousů břitvou" },
  { name: "Střih + úprava vousů", price: "od 749 Kč", description: "Kompletní péče o vlasy i vousy" },
  { name: "Senior pánský střih (65+)", price: "od 249 Kč", description: "Zvýhodněná cena pro seniory" },
  { name: "Dětský střih (1–15 let)", price: "od 299 Kč", description: "Trpělivý přístup k mladým zákazníkům" },
];

export const voucherBranches: VoucherBranch[] = [
  {
    name: "AK BARBERS Beroun 2",
    address: "Plzeňská 145/49, 266 01 Beroun-Město",
    url: "https://booqme.cz/cs/rezervace/ak-barbers-beroun",
  },
  {
    name: "AK BARBERS Praha 1",
    address: "Národní 949/19, 110 00 Staré Město",
    url: "https://booqme.cz",
  },
  {
    name: "AK BARBERS Plzeň",
    address: "Gerská 2030/23, 323 00 Plzeň",
    url: "https://booqme.cz/cs/rezervace/ak-barbers-plzen1",
  },
  {
    name: "AK BARBERS MÁJ",
    address: "Národní 63/26, 110 00 Nové Město",
    url: "https://booqme.cz",
  },
  {
    name: "AK BARBERS Nitra",
    address: "OC MLYNY, Štefánikova trieda 35/61, 949 01 Nitra",
    url: "https://booqme.sk",
  },
];

export const jobPositions: JobPosition[] = [
  {
    title: "Barber – zkušený",
    location: "Všechny pobočky CZ/SK",
    type: "Plný úvazek",
    description:
      "Hledáme zkušené barbery s praxí minimálně 1 rok. Nabízíme férové podmínky, profesionální zázemí a možnost růstu v rámci sítě AK Barbers.",
  },
  {
    title: "Barber – začátečník",
    location: "Všechny pobočky CZ/SK",
    type: "Plný úvazek",
    description:
      "Jste nadšení do barberingu a chcete se učit od těch nejlepších? Projdete naším zaškolovacím programem pod vedením Adriana Křižana.",
  },
  {
    title: "Recepční / Koordinátor pobočky",
    location: "Praha, Beroun",
    type: "Plný / částečný úvazek",
    description:
      "Komunikativní osobnost pro správu rezervací, péči o zákazníky a koordinaci chodu pobočky.",
  },
];

export const benefits: Benefit[] = [
  {
    icon: "Scissors",
    title: "Profesionální zázemí",
    description: "Prémiové vybavení a produkty ve všech pobočkách",
  },
  {
    icon: "GraduationCap",
    title: "Vzdělávání",
    description: "Pravidelné školení a workshopy v rámci AK Academy",
  },
  {
    icon: "TrendingUp",
    title: "Kariérní růst",
    description: "Možnost stát se vedoucím pobočky nebo lektorem",
  },
  {
    icon: "Users",
    title: "Skvělý tým",
    description: "Přátelská atmosféra a silná barberská komunita",
  },
  {
    icon: "Banknote",
    title: "Férové podmínky",
    description: "Atraktivní odměňování a bonusy za výkon",
  },
  {
    icon: "MapPin",
    title: "Flexibilita",
    description: "Možnost výběru pobočky po celé ČR a SR",
  },
];
